package errgroup

import "testing"

func TestErrGroupWithResult(t *testing.T) {
	runErrGroupWithResult()
}
